name: Deploy Develop

on:
  push:
    branches: [develop]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_MASTER }}
          username: ${{ secrets.HOST_MASTER_USER }}
          key: ${{ secrets.HOST_MASTER_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/hoenn-workflow
            git checkout develop
            git pull -f origin develop
            yarn
            yarn build
            yarn migration:up
            pm2 restart workflow
